<?php

/**
 * @file
 * The DFP module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Routing\RouteMatchInterface;

// @todo move constants to interface
//define('DFP_GOOGLE_TAG_SERVICES_URL', 'www.googletagservices.com/tag/js/gpt.js');
//define('DFP_GOOGLE_SHORT_TAG_SERVICES_URL', 'pubads.g.doubleclick.net/gampad');
define('DFP_GOOGLE_TAG_SERVICES_URL', 'example.com/www.googletagservices.com/tag/js/gpt.js');
define('DFP_GOOGLE_SHORT_TAG_SERVICES_URL', 'example.com/pubads.g.doubleclick.net/gampad');

/**
 * Implements hook_help().
 */
function dfp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.dfp':
      $output = '<p>' . t('The Doubleclick For Publishers (DFP) module allows you to integrate Google Publisher Tags onto your site.') . '</p>';
      $output .= '<p>' . t('This module provides you with a general settings form as well as the ability to create a tag (with all its associated data) in the database. You can display your ads as blocks, or add a simple bit of php to your tpl.php file(s) within your theme to indicate where specific tags should be displayed.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function dfp_theme() {
  return [
    'dfp_tag' => [
      'variables' => [
        'tag' => NULL,
      ]
    ],
    'dfp_short_tag' => [
      'variables' => [
        'tag' => NULL,
        'url_jump' => NULL,
        'url_ad' => NULL,
      ],
    ],
    'dfp_js' => [
      'variables' => [
        'google_tag_services_url' => NULL,
        'async_rendering' => NULL,
        'single_request' => NULL,
        'collapse_empty_divs' => NULL,
        'disable_init_load' => NULL,
        'targeting' => [],
      ],
    ],
    'dfp_slot_definition_js' => [
      'variables' => [
        'tag' => NULL,
      ]
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function dfp_page_attachments(array &$page) {
  // @todo Work out how to add this only when required.
  $global_settings = \Drupal::config('dfp.settings');
  $targeting = $global_settings->get('targeting');
  \Drupal::moduleHandler()->alter('dfp_global_targeting', $targeting);
  $targeting = \Drupal\dfp\View\TagView::formatTargeting($targeting, \Drupal::service('dfp.token'), \Drupal::moduleHandler());
  $build = [
    '#theme' => 'dfp_js',
    '#google_tag_services_url' => DFP_GOOGLE_TAG_SERVICES_URL,
    '#async_rendering' => $global_settings->get('async_rendering'),
    '#single_request' => $global_settings->get('single_request'),
    '#collapse_empty_divs' => $global_settings->get('collapse_empty_divs'),
    '#disable_init_load' => $global_settings->get('disable_init_load'),
    '#targeting' => $targeting,
  ];
  $page['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#value' => \Drupal::service('renderer')->renderPlain($build),
    ],
    'dfp-setup',
  ];
  if (isset($page['#cache']['tags'])) {
    $page['#cache']['tags'] = Cache::mergeTags($page['#cache']['tags'], $global_settings->getCacheTags());
  }
  else {
    $page['#cache']['tags'] = $global_settings->getCacheTags();
  }
}
