<?php

/**
 * @file
 * Installation file for DFP module.
 */

///**
// * Implements hook_enable().
// */
//function dfp_enable() {
//  $t = get_t();
//
//  if (!module_exists('token')) {
//    drupal_set_message($t('While it is not required, the Doubleclick for Publishers administration forms are vastly improved by using the <a href="http://drupal.org/project/token">token module</a>.'));
//  }
//}
